name: Flutter CI

# This workflow is triggered on pushes to the repository.
concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
    - main

  workflow_dispatch:
    inputs:
      comments:
        description: 'Comments'
        required: true
        default: 'Manual build Actions'
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    env:
      AAB_PATH: build/app/outputs/apk/release/app-release.apk
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ vars.JAVA_VERSION }}
    
    - name: Flutter action
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: ${{ vars.FLUTTER_VERSION }}
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .flutter-plugins-dependencies
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    - run: flutter test
    
    # Build apk.
    - run: flutter build apk
    
    # Upload generated apk to the artifacts.
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ env.AAB_PATH }}